name: Build/Release NoteVault

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Increment version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npm version patch -m "chore(release): %s [skip ci]"
          git push origin main --tags

  build:
    needs: prepare-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo snap install snapcraft --classic
          sudo apt-get update
          sudo apt-get install -y fakeroot dpkg

      - name: Install dependencies
        run: npm install

      - name: Build and Publish (Windows)
        if: matrix.os == 'windows-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run package:win -- --publish always

      - name: Build and Publish (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run package:linux -- --publish always

      - name: Upload Build Artifact (Windows)
        if: always() && matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: NoteVault-Windows-Installer
          path: dist/*.exe
          retention-days: 7

      - name: Upload Build Artifact (Linux)
        if: always() && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: NoteVault-Linux-Installer
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.snap
          retention-days: 7
